[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "textsummarizer"
version = "0.0.0"
authors = [
  { name = "vishv0111", email = "vishv0111@gmail.com" },
]
description = "A text summarization project"
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]
